wip: walk the module graph
rehearsal-js/rehearsal-js pull request #1053
Opened 2023-05-17 20:02 UTC by chadhietala

this is still a wip

2023-05-17 20:13 UTC, egorio commented on packages/migration-graph/src/discover-services.ts
> +export function discoverServiceDependencies(
👍 💯

2023-05-17 20:21 UTC, egorio commented on packages/cli/src/commands/fix/command.ts
> +  .action(async (srcPath: string, options: FixCommandOptions) => {
could you please use targetSrcPath... just trying to make it clearer down the code.

2023-05-17 20:24 UTC, egorio commented on packages/cli/src/commands/fix/tasks/convert-task.ts
> +      const { projectName, orderedFiles } = ctx;
I also find that using context is like using global var, very hard to keep mental model of the app in the memory while debugging. 

I would prefer to pass the result of one task to the next one input... but probably not in this PR :)

2023-05-17 20:53 UTC, egorio commented on packages/cli/src/utils/prereq-checks.ts
> +  const tsConfigPath = resolve(basePath, 'tsconfig.json');
I think this: https://github.com/rehearsal-js/rehearsal-js/blob/6363ff411e8b24cd1badd62bd4de3e437218a111/packages/migrate/src/migrate.ts#L69-L73

2023-05-17 21:07 UTC, egorio commented on packages/cli/src/utils/prereq-checks.ts
> +  const tsConfigPath = resolve(basePath, 'tsconfig.json');
https://github.com/rehearsal-js/rehearsal-js/issues/1056

2023-05-18 14:47 UTC, lynchbomb requested changes

2023-05-18 14:47 UTC, lynchbomb commented on packages/cli/src/commands/graph/tasks/graphOrderTask.ts
> +import { Response } from './types.js';
import type { Response } from './types.js';

2023-05-18 14:47 UTC, lynchbomb commented on packages/cli/src/commands/graph/tasks/graphOrderTask.ts
> +      if (!output && !skipPrompt) {
`!skipPrompt` now that the prompt is removed we can remove this conditional and wherever its being set

2023-05-18 14:47 UTC, lynchbomb commented on packages/cli/src/commands/graph/tasks/graphWorker.ts
> +import { GraphWorkerOptions } from './types.js';
import type { GraphWorkerOptions } from './types.js';

2023-05-18 14:47 UTC, lynchbomb commented on packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
> +[TITLE]   22 errors caught by rehearsal
Will you double check the reduction in errors caught and fixes is accurate?

2023-05-18 14:47 UTC, lynchbomb commented on packages/cli/test/commands/fix/init-task.test.ts
> +    const sanitizedAbsPaths = ctx.orderedFiles?.map((path) => {
should we append `rel/abs` on this >> `ctx.orderedFiles`

2023-05-18 19:43 UTC, lynchbomb approved these changes

2023-05-18 19:44 UTC, merged

2026-04-21 20:00 UTC, NullVoxPopuli commented
idk if it helps for gjs/gts, but we have these tools now:
- github.com/NullVoxPopuli/ember-estree - also does hbs? I forget, tbh
- github.com/NullVoxPopuli/zmod-ember

Tho, I see you're using: https://github.com/guybedford/es-module-lexer now
I'm using that here: https://github.com/NullVoxPopuli/limber/pull/1995

so maybe you don't need anything else