feat: add glint errors in output; drop comment insertion in hbs
rehearsal-js/rehearsal-js pull request #1133
Opened 2023-06-14 22:13 UTC by wondersloth

## Summary
- Re-enable parsing .hbs files in graph.
- Abort adding glint directives `{{! @glint-expect-error}}` to hbs contexts.
- Update reporter to aggregate glint errors.
- `fix` command output now prints total glint errors found

## Details
Changes across packages:
**cli**
- Update CLI report output (fix) to optionally display **glint** error summary

**migrate*
- Adds a test in `migrate` package for validating the errors with `ReportItemType.glint` show on the reporter.
- Validates that glint errors for `ReportItemType.glint` exist in `rehearal-report.json` output.

**migratiojn-graph**
- Adds `.hbs` back into graph creation
- I ignored .hbs after I discovered the injection issue.
- This is necessary so we can feed `.hbs` files into the GlintComment and GlintReport plugins.
- This will now show that `./path/to/some.hbs` will be processed during fix.

**reporter**
- Add `glint` to `ReportItemType` enum
- Expose `ReportItemType` enum
- Add API for adding a glint diagnostic to the report.

2023-06-14 23:54 UTC, egorio submitted a review, later dismissed

2023-06-15 09:52 UTC, lynchbomb requested changes
"Validates that glint errors for ReportItemType.glint exist in rehearal-report.json output."


With this change we are not suppressing the glint errors with a directive. Essentially we are only counting the glint errors. 

1. Will you validate the source-map in the SARIF rehearsal-report is pointing to the correct line for .gts and .hbs files.
2. Previously you could run "rehearsal fix" against your app. Rehearsal would fix and suppress errors. This allowed for partial migrations. With this change is this still possible? (My understanding is since now we are no longer suppressing glint errors it is not).

2023-06-15 20:45 UTC, wondersloth commented
>Previously you could run "rehearsal fix" against your app. Rehearsal would fix and suppress errors. This allowed for partial migrations. With this change is this still possible? (My understanding is since now we are no longer suppressing glint errors it is not).

@lynchbomb 

Partial migrations of an hbs context was never possible, since we could not reliably suppress all errors and not break glimmer syntax.

When migrating voyager, we found the edge cases for errors that we could not suppress. (replicated in #1080).

Our options for partial migration now:
We _could_ suppress the whole file hbs/region if we find errors.

2023-06-16 15:08 UTC, lynchbomb commented
@wondersloth once #1129 lands it should mitigate the majority of nested cases. After this lands I think it makes sense to:

> Suppress what errors we can safely suppress, then add a no-check if we find one of the nested cases. Would require parsing the hbs and understanding glimmer syntax for injection.

Otherwise without #1129 the majority of hbs errors will be related to missing types ie component signatures.

We can merge this PR will the next followup being #1129 and then ^^^

2023-06-16 15:09 UTC, lynchbomb approved these changes

2023-06-16 15:09 UTC, merged