fix: prettier.format() return empty string for some .gts files
rehearsal-js/rehearsal-js pull request #1236
Opened 2023-08-15 22:50 UTC by egorio

Prettier 3.0.0 doesn't fail on .gts files.

This solution can unblock users, but we probably need to think about using the project's version of prettier (and eslint?) to format the project's content (probably even run bin files).

2023-08-15 23:01 UTC, wondersloth requested changes
Update the README.md

2023-08-15 23:21 UTC, wondersloth commented on package.json
> +    "@types/prettier": "^3.0.0",
We don't need the `@types/prettier` https://prettier.io/blog/2023/07/05/3.0.0.html#api-2

2023-08-15 23:21 UTC, wondersloth commented
Also, the glimmerx prettier plugin will no longer work in prettier 3.0. So we need to document that it needs to be updated.

2023-08-15 23:25 UTC, wondersloth commented
There are still a lot of fixtures and test-cases that use `2.*` dependencies. We need to ensure we have back compat on any update or update all instances.

2023-08-16 00:29 UTC, wondersloth requested changes

2023-08-16 16:38 UTC, lynchbomb commented
Lets just:
- bump prettier as a rehearsal dep to ^3
- bump prettier pre-flight check as hard dev-dep to ^3 here: (https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/prereqs.ts#L39)
- we might _also_ want to bump typescript in the pre-flight check to ^5 with this change
- after this lands we will release a new major

2023-08-17 01:13 UTC, closed without merging