feat: discover ember service dependency information from a file
rehearsal-js/rehearsal-js pull request #403
Opened 2022-09-29 21:38 UTC by wondersloth

This is work to support the #390.
This PR addresses parsing a single source file and finding the usages of `@ember/service`. 
It returns an array of service meta data.

```
type EmberInferredServiceDependency = {
  addonName?: string;
  serviceName: string;
};
```

This implementation should not try resolve the services just parse and extract meaningful meta data.

2022-09-29 21:52 UTC, lynchbomb commented
Since this implementation is specific to Ember shouldn't we have it live in `migration-graph-ember` and not `migration-graph`?

2022-09-29 22:49 UTC, wondersloth commented
> Since this implementation is specific to Ember shouldn't we have it live in `migration-graph-ember` and not `migration-graph`?

- [ ] Move to `migration-graph-ember`

I can move it over there now. My other work is sitting in `migration-graph` I hadn't thought about organization yet because I don't like having to "prepare" across packages.

2022-10-03 17:35 UTC, chadhietala requested changes
Overall looks good to me. Just a couple things that I think need to be fixed.

2022-10-03 17:35 UTC, chadhietala commented on packages/migration-graph-ember/src/utils/discover-ember-service-dependencies.ts
> +  // In the case of re-assignment from ineject as service, we walk the specifiers
```suggestion
In the case of re-assignment from inject as service, we walk the specifiers
```

2022-10-03 17:35 UTC, chadhietala commented on packages/migration-graph-ember/src/utils/discover-ember-service-dependencies.ts
> +    throw new Error('Unexpected Error: No classes found despite having imported @ember/service.');
I don't think we want to throw in the case. Probably should just return out with an empty result.

2022-10-03 17:49 UTC, chadhietala commented
Please make sure to migrate the ember graph stuff to use SWC instead of babel

2022-10-03 17:56 UTC, lynchbomb commented
https://github.com/rehearsal-js/rehearsal-js/issues/365

2022-10-18 19:15 UTC, lynchbomb approved these changes

2022-10-18 20:19 UTC, merged