feat: adding migration summary
rehearsal-js/rehearsal-js pull request #462
Opened 2022-11-28 23:53 UTC by haochuan

As we discussed in #451, running `tsc` after the JS->TS conversion seems unnecessary, since we are expecting to catch all the errors via the CLI. This PR removes `tsc` command, and adding a summary message after the actual conversion like:

```
✔ 30 JS files has been converted to TS, and there are 552 errors caught by rehearsal
  - 3 have been fixed automatically by rehearsal
  - 549 have been updated with @ts-ignore @rehearsal TODO which need further manual check
```

This PR also update the report flag, to have `json` report by default, and update the report formatter in `migrate`, to match the same in `upgrade` command.

2022-11-30 18:03 UTC, lynchbomb requested changes

2022-11-30 18:03 UTC, lynchbomb commented on packages/cli/src/commands/migrate.ts
> +    ['json']
we want the default to be sarif

2022-11-30 18:03 UTC, lynchbomb commented on packages/cli/test/commands/migrate.test.ts
>        cwd: basePath, // still run cli in basePath
`cwd: basePath` is causing failures ... if you rebase this will/should be removed

2022-12-01 19:54 UTC, haochuan commented
Resolved overlaps and conflict with current master

2022-12-01 20:04 UTC, lynchbomb approved these changes

2022-12-01 20:30 UTC, merged