chore: add migrate-by-directory in md
rehearsal-js/rehearsal-js pull request #789
Opened 2023-02-27 17:10 UTC by brendaHuang

Based on feedback

2023-02-27 17:43 UTC, lynchbomb commented
@brendaHuang can we also update the help strings in the cli command itself to match

2023-02-27 17:44 UTC, lynchbomb requested changes
see comment

2023-02-27 18:34 UTC, brendaHuang commented
@lynchbomb done

2023-02-28 15:12 UTC, lynchbomb approved these changes

2023-02-28 15:13 UTC, merged