WIP feat(cli): init command and skip configs
rehearsal-js/rehearsal-js pull request #805
Opened 2023-03-03 21:18 UTC by haochuan

2023-03-03 21:22 UTC, lynchbomb requested changes

2023-03-03 21:22 UTC, lynchbomb commented on packages/cli/src/commands/migrate/init-command.ts
> +  const tasks = [
the functionality we are looking for would make this child command atomic. we can combine the tasks in the migrate/index.ts command. for this command it shouldn't run any sibling tasks. 

`rehearsal migrate` <<< will run the tasks including init
`rehearsal migrate init` <<< will only run init

2023-03-03 21:41 UTC, haochuan commented
Some notes and stuff to discuss:

1. What would `migrate init` do?

From a user perspective, `migrate init` would do

- depInstallTask: dependency installation
- tsConfigTask: how to handle `tsconfig.json`
- lintConfigTask: how to handle `.eslintrc`
- createScriptsTask: add additional scripts in `package.json`

Currently the existed `--init` option would run:

```
 const tasks = [
    await validateTask(options, logger),
    await initTask(options),
    await depInstallTask(options),
    await tsConfigTask(options),
    await lintConfigTask(options),
    await createScriptsTask(options),
  ];
```

2. `migrate init` vs the actual `initTask`

Current `initTask` !== what we should run in `migrate init`. `initTask` would prepare stuff for the rest tasks in the CLI, not for the end users.

3. Do we want to add option to skip one/multi tasks in `migrate init`?
4. Do we want to add option to skip `migrate init` when running `migrate`?

2023-03-06 22:42 UTC, haochuan commented
After discussion with @lynchbomb we need to:

- create new subcommand `rehearsal migrate init`
  - do dep install, ts setup, lint setup, script setup
  - each task should be smart enough to check if it should run
    - in ts setup with user config, check for strict mode
  - in dep install task, have a better UI and error handling message, to let the user know what exactly goes wrong, and what's the next action
 
- `rehearsal migarte`
   - also run `migrate init`
   - new options `--skip-init`, but hide it in help text

2023-03-08 01:46 UTC, haochuan commented
> @haochuan is this ready for review?

@lynchbomb yeah but saw a lint error, need to fix that first.

I was trying to use `typescript.parseJsonConfigFileContent` to read the extends in `tsconfig.json`, but seems import `typescript` is not allowed here, need to figure out another way

2023-03-08 02:12 UTC, haochuan commented
Removed `typescript` import and use [`get-tsconfig`](https://github.com/privatenumber/get-tsconfig) to parse extensions. All lints and tests passed in my local.

2023-03-08 13:06 UTC, lynchbomb approved these changes

2023-03-08 13:07 UTC, lynchbomb commented
Awesome work! This is a much needed workflow.

2023-03-08 17:59 UTC, merged