sequential tests for ember
rehearsal-js/rehearsal-js pull request #884
Opened 2023-03-25 00:11 UTC by brendaHuang-2023

sequential tests for ember

2023-03-28 16:21 UTC, brendaHuang-2023 commented
This PR needs the code changes from other test PRs, mainly the added dependencies in test-support/fixtures/ember/addon-template project. Will merge this PR after the others have been merged.

2023-03-31 14:53 UTC, brendaHuang-2023 commented
THIS PR WILL BE THE LAST OF ALL TEST PRS TO MERGE. Before it's merged, I will need to retrigger the CI tests even though it may have passed earlier.

2023-04-03 15:11 UTC, lynchbomb commented on packages/cli/test/commands/migrate/sequential.ember-addon.test.ts
> +describe('Task: sequential - ember addon', () => {
^^^ and the delta from this test vs the other migrate test eg. e2e config, e2e ...

2023-04-03 15:15 UTC, lynchbomb commented on packages/cli/test/commands/migrate/sequential.ember-app.test.ts
> +        expect(appFiles).toContain('app.ts');
these are only checking that `git mv` worked, which isn't super helpful. this test should be focused on running the migration **sequentially**. there should be a delta between running the migration as a single pass (e2e tests) vs in sequence (this test) and then testing against that delta

2023-04-03 15:19 UTC, lynchbomb requested changes
lets be sure the tests around sequential migration are focused on just that. eg

- validate the project was partially migrated
- ... run sequential migration on remainder
- validate the entire project is now migrated

//////

- validate the project was partially migrated
- ... run sequential migration on 1 of N child packages
- validate this child package is migrated
- N of N child packages are now migrated

2023-04-19 20:29 UTC, closed without merging